
AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - bin/*
  TargetRubyVersion: 2.4

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Metrics/LineLength:
  Max: 120
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/CommandLiteral:
  Enabled: true
  EnforcedStyle: percent_x
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
